
#set flags and compiler



CXX      	= g++-4.9
CXXFLAGS	= -std=c++11 -g -O3 -framework Accelerate -larmadillo -Wall 
SRC 	= 
SOURCES  	=  ../solvers/serialSolver.cpp
EXE = serialSolver

all:
	$(CXX) $(SOURCES) $(CXXFLAGS) -o $(EXE) 









